# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Main company')),
                ('annual_earning', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Annual earning')),
            ],
            options={
                'db_table': 'main_company',
                'verbose_name': 'MainCompany',
            },
        ),
        migrations.CreateModel(
            name='SubsidiaryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Subsidiary company')),
                ('annual_earning', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Annual earning')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('main_company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_from_main', to='companies.MainCompany')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_from_sub', to='companies.SubsidiaryCompany')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
                'verbose_name': 'SubsidiaryCompany',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
